### ISSUE TITLE
Debug Engine Code

### ISSUE THREAD

**Issue by leonfs** [botman99/ue4-xcode-vscode-mac#13]
Hi - thanks for putting the setup instructions on GH, very useful.

I managed to get my project debugging, but I can't debug the UE engine code, I only see assembly code. I tried including the debugging symbols of my engine version (5.03) from the Epic Launcher, but I can't get to debug the engine's code. 

Any hints on how to do it? I'm running on a Mac M1. 

Thanks again.
Leo

**Comment by botman99** [comment]
Did you download the engine source code from GitHub and build the engine from source?  If you installed from the Epic Game Launcher, you won't have any engine source code.  If you download the engine source from GitHub, you won't need to download the symbols since the compiler will generate the symbol files when building.

**Comment by leonfs** [comment]
Thanks, @botman99. This is what I ended up doing, and it worked.
